module.exports =  agents = [
  { name: "Astra", img: "https://placehold.co/400" },
  { name: "Breach", img: "https://placehold.co/400" },
  { name: "Brimstone", img: "https://placehold.co/400" },
  { name: "Chamber", img: "https://placehold.co/400" },
  { name: "Clove", img: "https://placehold.co/400" },
  { name: "Cypher", img: "https://placehold.co/400" },
  { name: "Jett", img: "https://placehold.co/400" },
  { name: "KAY/O", img: "https://placehold.co/400" },
  { name: "Killjoy", img: "https://placehold.co/400" },
  { name: "Neon", img: "https://placehold.co/400" },
  { name: "Omen", img: "https://placehold.co/400" },
  { name: "Phoenix", img: "https://placehold.co/400" },
  { name: "Raze", img: "https://placehold.co/400" },
  { name: "Reyna", img: "https://placehold.co/400" },
  { name: "Sage", img: "https://placehold.co/400" },
  { name: "Skye", img: "https://placehold.co/400" },
  { name: "Sova", img: "https://placehold.co/400" },
  { name: "Viper", img: "https://placehold.co/400" },
  { name: "Yoru", img: "https://placehold.co/400" },
];
